import type { AppState, FinancialRecord, InventoryItem, Product, Purchase, Recipe } from "./domain";

const today = new Date().toISOString().slice(0, 10);
const month = today.slice(0, 7);

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-espresso",
    name: "Espresso",
    category: "Cafes",
    price: 7.5,
    cost: 1.8,
    stock: 999,
    stockMin: 0,
    status: "active",
    recipeId: "rec-espresso",
  },
  {
    id: "prod-cappuccino",
    name: "Cappuccino L'Chef",
    category: "Cafes",
    price: 14,
    cost: 4.2,
    stock: 999,
    stockMin: 0,
    status: "active",
    recipeId: "rec-cappuccino",
  },
  {
    id: "prod-chocolate-quente",
    name: "Chocolate Quente Amazonico",
    category: "Bebidas Quentes",
    price: 16,
    cost: 5.4,
    stock: 999,
    stockMin: 0,
    status: "active",
    recipeId: "rec-chocolate-quente",
  },
  {
    id: "prod-brownie",
    name: "Brownie Bean-to-Bar",
    category: "Doces",
    price: 18,
    cost: 5.1,
    stock: 42,
    stockMin: 20,
    status: "active",
    recipeId: "rec-brownie",
  },
  {
    id: "prod-cookie",
    name: "Cookie de Chocolate",
    category: "Doces",
    price: 12,
    cost: 2.8,
    stock: 18,
    stockMin: 20,
    status: "active",
    recipeId: "rec-cookie",
  },
  {
    id: "prod-bolo-cenoura",
    name: "Bolo de Cenoura com Ganache",
    category: "Bolos",
    price: 22,
    cost: 7.2,
    stock: 9,
    stockMin: 8,
    status: "active",
    recipeId: "rec-bolo-cenoura",
  },
  {
    id: "prod-coado",
    name: "Cafe Coado Especial",
    category: "Cafes",
    price: 9,
    cost: 2.1,
    stock: 999,
    stockMin: 0,
    status: "active",
    recipeId: "rec-coado",
  },
  {
    id: "prod-croissant",
    name: "Croissant",
    category: "Salgados",
    price: 11,
    cost: 3.6,
    stock: 24,
    stockMin: 15,
    status: "active",
    recipeId: "rec-croissant",
  },
  {
    id: "prod-pao-queijo",
    name: "Pao de Queijo",
    category: "Salgados",
    price: 6,
    cost: 1.5,
    stock: 80,
    stockMin: 30,
    status: "active",
    recipeId: "rec-pao-queijo",
  },
  {
    id: "prod-chocolates",
    name: "Caixa de Chocolates Artesanais",
    category: "Chocolates",
    price: 68,
    cost: 24,
    stock: 12,
    stockMin: 10,
    status: "active",
    recipeId: "rec-chocolates",
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: "inv-cafe",
    name: "Cafe especial",
    category: "Cafe",
    quantity: 8.5,
    unit: "kg",
    minQuantity: 5,
    cost: 75,
    expiresAt: "2026-08-12",
    lot: "CAF-2605",
  },
  {
    id: "inv-leite",
    name: "Leite",
    category: "Laticinios",
    quantity: 32,
    unit: "L",
    minQuantity: 20,
    cost: 6.5,
    expiresAt: "2026-06-04",
    lot: "LEI-0527",
  },
  {
    id: "inv-chocolate",
    name: "Chocolate",
    category: "Chocolate",
    quantity: 4.2,
    unit: "kg",
    minQuantity: 5,
    cost: 180,
    expiresAt: "2026-12-01",
    lot: "CHO-70",
  },
  {
    id: "inv-cacau",
    name: "Cacau",
    category: "Cacau",
    quantity: 2.1,
    unit: "kg",
    minQuantity: 3,
    cost: 95,
    expiresAt: "2026-07-30",
    lot: "CAC-0626",
  },
  {
    id: "inv-acucar",
    name: "Acucar",
    category: "Secos",
    quantity: 15,
    unit: "kg",
    minQuantity: 8,
    cost: 4.8,
    expiresAt: "2027-01-20",
  },
  {
    id: "inv-farinha",
    name: "Farinha",
    category: "Secos",
    quantity: 22,
    unit: "kg",
    minQuantity: 10,
    cost: 6.2,
    expiresAt: "2026-09-15",
  },
  {
    id: "inv-manteiga",
    name: "Manteiga",
    category: "Laticinios",
    quantity: 9,
    unit: "kg",
    minQuantity: 4,
    cost: 50,
    expiresAt: "2026-06-20",
  },
  {
    id: "inv-ovos",
    name: "Ovos",
    category: "Frescos",
    quantity: 180,
    unit: "un",
    minQuantity: 60,
    cost: 1,
    expiresAt: "2026-06-10",
  },
  {
    id: "inv-creme",
    name: "Creme de leite",
    category: "Laticinios",
    quantity: 16,
    unit: "L",
    minQuantity: 6,
    cost: 14,
    expiresAt: "2026-06-14",
  },
  {
    id: "inv-embalagem",
    name: "Embalagens",
    category: "Embalagens",
    quantity: 48,
    unit: "un",
    minQuantity: 30,
    cost: 4.2,
  },
  {
    id: "inv-croissant",
    name: "Croissant cru",
    category: "Congelados",
    quantity: 24,
    unit: "un",
    minQuantity: 15,
    cost: 3.6,
    expiresAt: "2026-06-30",
  },
  {
    id: "inv-pao-queijo",
    name: "Pao de queijo congelado",
    category: "Congelados",
    quantity: 80,
    unit: "un",
    minQuantity: 30,
    cost: 1.5,
    expiresAt: "2026-07-15",
  },
];

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: "rec-espresso",
    productId: "prod-espresso",
    name: "Espresso",
    yieldQty: 1,
    version: "v1.0",
    preparation: "Moer cafe fresco e extrair 30 ml.",
    validityDays: 0,
    desiredMargin: 70,
    items: [{ inventoryItemId: "inv-cafe", quantity: 0.012, unit: "kg" }],
  },
  {
    id: "rec-cappuccino",
    productId: "prod-cappuccino",
    name: "Cappuccino L'Chef",
    yieldQty: 1,
    version: "v1.2",
    preparation: "Extrair espresso, vaporizar leite e finalizar com cacau.",
    validityDays: 0,
    desiredMargin: 68,
    items: [
      { inventoryItemId: "inv-cafe", quantity: 0.012, unit: "kg" },
      { inventoryItemId: "inv-leite", quantity: 0.18, unit: "L" },
      { inventoryItemId: "inv-cacau", quantity: 0.006, unit: "kg" },
    ],
  },
  {
    id: "rec-chocolate-quente",
    productId: "prod-chocolate-quente",
    name: "Chocolate Quente Amazonico",
    yieldQty: 1,
    version: "v1.1",
    preparation: "Aquecer leite, chocolate e cacau ate textura cremosa.",
    validityDays: 0,
    desiredMargin: 66,
    items: [
      { inventoryItemId: "inv-leite", quantity: 0.22, unit: "L" },
      { inventoryItemId: "inv-chocolate", quantity: 0.018, unit: "kg" },
      { inventoryItemId: "inv-cacau", quantity: 0.006, unit: "kg" },
      { inventoryItemId: "inv-acucar", quantity: 0.012, unit: "kg" },
    ],
  },
  {
    id: "rec-brownie",
    productId: "prod-brownie",
    name: "Brownie Bean-to-Bar",
    yieldQty: 20,
    version: "v2.3",
    preparation: "Misturar secos e chocolate derretido, assar por 28 minutos.",
    validityDays: 5,
    desiredMargin: 70,
    items: [
      { inventoryItemId: "inv-chocolate", quantity: 0.4, unit: "kg" },
      { inventoryItemId: "inv-manteiga", quantity: 0.25, unit: "kg" },
      { inventoryItemId: "inv-acucar", quantity: 0.3, unit: "kg" },
      { inventoryItemId: "inv-farinha", quantity: 0.18, unit: "kg" },
      { inventoryItemId: "inv-ovos", quantity: 4, unit: "un" },
      { inventoryItemId: "inv-embalagem", quantity: 20, unit: "un" },
    ],
  },
  {
    id: "rec-cookie",
    productId: "prod-cookie",
    name: "Cookie de Chocolate",
    yieldQty: 24,
    version: "v1.4",
    preparation: "Porcionar massa gelada e assar sob demanda.",
    validityDays: 4,
    desiredMargin: 72,
    items: [
      { inventoryItemId: "inv-chocolate", quantity: 0.22, unit: "kg" },
      { inventoryItemId: "inv-manteiga", quantity: 0.18, unit: "kg" },
      { inventoryItemId: "inv-acucar", quantity: 0.28, unit: "kg" },
      { inventoryItemId: "inv-farinha", quantity: 0.35, unit: "kg" },
      { inventoryItemId: "inv-ovos", quantity: 2, unit: "un" },
    ],
  },
  {
    id: "rec-bolo-cenoura",
    productId: "prod-bolo-cenoura",
    name: "Bolo de Cenoura com Ganache",
    yieldQty: 12,
    version: "v1.0",
    preparation: "Assar bolo em forma alta e cobrir com ganache.",
    validityDays: 3,
    desiredMargin: 66,
    items: [
      { inventoryItemId: "inv-farinha", quantity: 0.45, unit: "kg" },
      { inventoryItemId: "inv-acucar", quantity: 0.35, unit: "kg" },
      { inventoryItemId: "inv-ovos", quantity: 4, unit: "un" },
      { inventoryItemId: "inv-chocolate", quantity: 0.24, unit: "kg" },
      { inventoryItemId: "inv-creme", quantity: 0.18, unit: "L" },
    ],
  },
  {
    id: "rec-coado",
    productId: "prod-coado",
    name: "Cafe Coado Especial",
    yieldQty: 1,
    version: "v1.0",
    preparation: "Coar em V60 com agua a 93 C.",
    validityDays: 0,
    desiredMargin: 70,
    items: [{ inventoryItemId: "inv-cafe", quantity: 0.016, unit: "kg" }],
  },
  {
    id: "rec-croissant",
    productId: "prod-croissant",
    name: "Croissant",
    yieldQty: 1,
    version: "v1.0",
    preparation: "Assar croissant congelado ate dourar.",
    validityDays: 1,
    desiredMargin: 65,
    items: [{ inventoryItemId: "inv-croissant", quantity: 1, unit: "un" }],
  },
  {
    id: "rec-pao-queijo",
    productId: "prod-pao-queijo",
    name: "Pao de Queijo",
    yieldQty: 1,
    version: "v1.0",
    preparation: "Assar porcoes congeladas por 18 minutos.",
    validityDays: 1,
    desiredMargin: 70,
    items: [{ inventoryItemId: "inv-pao-queijo", quantity: 1, unit: "un" }],
  },
  {
    id: "rec-chocolates",
    productId: "prod-chocolates",
    name: "Caixa de Chocolates Artesanais",
    yieldQty: 1,
    version: "v1.0",
    preparation: "Montar caixa com bombons sortidos e embalagem premium.",
    validityDays: 30,
    desiredMargin: 62,
    items: [
      { inventoryItemId: "inv-chocolate", quantity: 0.12, unit: "kg" },
      { inventoryItemId: "inv-cacau", quantity: 0.015, unit: "kg" },
      { inventoryItemId: "inv-embalagem", quantity: 1, unit: "un" },
    ],
  },
];

const financialRecords: FinancialRecord[] = [
  {
    id: "fin-aluguel",
    type: "expense",
    description: "Aluguel - Maio",
    amount: 4800,
    status: "open",
    category: "Administrativo",
    costCenter: "Loja",
    dueDate: `${month}-28`,
    competenceDate: `${month}-01`,
  },
  {
    id: "fin-energia",
    type: "expense",
    description: "Energia eletrica",
    amount: 920,
    status: "open",
    category: "Administrativo",
    costCenter: "Loja",
    dueDate: `${month}-29`,
    competenceDate: `${month}-01`,
  },
  {
    id: "fin-contador",
    type: "expense",
    description: "Contador",
    amount: 850,
    status: "overdue",
    category: "Administrativo",
    costCenter: "Backoffice",
    dueDate: `${month}-25`,
    competenceDate: `${month}-01`,
  },
  {
    id: "fin-folha",
    type: "expense",
    description: "Folha de pagamento",
    amount: 14200,
    status: "paid",
    category: "Folha",
    costCenter: "Operacao",
    dueDate: `${month}-05`,
    competenceDate: `${month}-01`,
    paidAt: `${month}-05T12:00:00.000Z`,
  },
  {
    id: "fin-marketing",
    type: "expense",
    description: "Campanha Dia dos Namorados",
    amount: 1800,
    status: "paid",
    category: "Marketing",
    costCenter: "Comercial",
    dueDate: `${month}-18`,
    competenceDate: `${month}-01`,
    paidAt: `${month}-18T12:00:00.000Z`,
  },
  {
    id: "fin-impostos",
    type: "expense",
    description: "Impostos estimados",
    amount: 6280,
    status: "open",
    category: "Impostos",
    costCenter: "Fiscal",
    dueDate: `${month}-30`,
    competenceDate: `${month}-01`,
  },
  {
    id: "fin-evento",
    type: "revenue",
    description: "Evento corporativo XPTO",
    amount: 4200,
    status: "open",
    category: "Eventos",
    costCenter: "Comercial",
    dueDate: `${month}-30`,
    competenceDate: `${month}-01`,
  },
  {
    id: "fin-casamento",
    type: "revenue",
    description: "Encomenda casamento Rocha",
    amount: 1800,
    status: "open",
    category: "Encomendas",
    costCenter: "Confeitaria",
    dueDate: `${month}-29`,
    competenceDate: `${month}-01`,
  },
];

const purchases: Purchase[] = [
  {
    id: "pur-cafe",
    supplierId: "sup-aurora",
    supplierName: "Fazenda Aurora",
    invoiceNumber: "NF-00123",
    status: "received",
    paymentStatus: "open",
    paymentTerms: "Boleto 30 dias",
    createdAt: `${month}-21T10:00:00.000Z`,
    receivedAt: `${month}-22T11:00:00.000Z`,
    total: 1280,
    items: [
      {
        inventoryItemId: "inv-cafe",
        name: "Cafe especial",
        quantity: 12,
        unit: "kg",
        unitCost: 75,
      },
    ],
  },
  {
    id: "pur-leite",
    supplierId: "sup-laticinios",
    supplierName: "Laticinios Bela Vista",
    invoiceNumber: "NF-00876",
    status: "paid",
    paymentStatus: "paid",
    paymentTerms: "PIX",
    createdAt: `${month}-20T09:00:00.000Z`,
    receivedAt: `${month}-20T13:00:00.000Z`,
    paidAt: `${month}-20T14:00:00.000Z`,
    total: 740,
    items: [
      { inventoryItemId: "inv-leite", name: "Leite", quantity: 80, unit: "L", unitCost: 6.5 },
      {
        inventoryItemId: "inv-creme",
        name: "Creme de leite",
        quantity: 10,
        unit: "L",
        unitCost: 14,
      },
    ],
  },
  {
    id: "pur-cacau",
    supplierId: "sup-cacau",
    supplierName: "Cacau Amazonico Ltda",
    invoiceNumber: "NF-01234",
    status: "order",
    paymentStatus: "open",
    paymentTerms: "Boleto 21 dias",
    createdAt: `${month}-24T15:00:00.000Z`,
    total: 2150,
    items: [
      {
        inventoryItemId: "inv-chocolate",
        name: "Chocolate",
        quantity: 8,
        unit: "kg",
        unitCost: 180,
      },
      { inventoryItemId: "inv-cacau", name: "Cacau", quantity: 5, unit: "kg", unitCost: 95 },
    ],
  },
  {
    id: "pur-embalagens",
    supplierId: "sup-embalagens",
    supplierName: "Embalagens Premium",
    invoiceNumber: "NF-00422",
    status: "paid",
    paymentStatus: "paid",
    paymentTerms: "Cartao",
    createdAt: `${month}-18T12:00:00.000Z`,
    receivedAt: `${month}-19T09:00:00.000Z`,
    paidAt: `${month}-19T09:20:00.000Z`,
    total: 640,
    items: [
      {
        inventoryItemId: "inv-embalagem",
        name: "Embalagens",
        quantity: 160,
        unit: "un",
        unitCost: 4.2,
      },
    ],
  },
];

export const INITIAL_STATE: AppState = {
  users: [
    {
      id: "usr-admin",
      name: "Renata Alves",
      email: "renata@lchef.com.br",
      role: "admin",
      active: true,
    },
    {
      id: "usr-manager",
      name: "Bruno Castro",
      email: "bruno@lchef.com.br",
      role: "manager",
      active: true,
    },
    {
      id: "usr-cashier",
      name: "Diego Lopes",
      email: "caixa@lchef.com.br",
      role: "cashier",
      active: true,
    },
    {
      id: "usr-kitchen",
      name: "Camila Duarte",
      email: "cozinha@lchef.com.br",
      role: "kitchen",
      active: true,
    },
    {
      id: "usr-finance",
      name: "Elaine Souza",
      email: "financeiro@lchef.com.br",
      role: "finance",
      active: true,
    },
    {
      id: "usr-accountant",
      name: "Contabilidade L'Chef",
      email: "contador@lchef.com.br",
      role: "accountant",
      active: true,
    },
  ],
  currentUserId: undefined,
  units: ["L'Chef Cafe", "L'Chef Chocolateria", "Grupo L'Chef"],
  products: INITIAL_PRODUCTS,
  inventoryItems: INITIAL_INVENTORY,
  inventoryMovements: [],
  recipes: INITIAL_RECIPES,
  suppliers: [
    {
      id: "sup-aurora",
      name: "Fazenda Aurora",
      document: "12.345.678/0001-90",
      category: "Cafe",
      paymentTerms: "30 dias",
      status: "active",
    },
    {
      id: "sup-cacau",
      name: "Cacau Amazonico Ltda",
      document: "23.456.789/0001-12",
      category: "Chocolate",
      paymentTerms: "21 dias",
      status: "active",
    },
    {
      id: "sup-laticinios",
      name: "Laticinios Bela Vista",
      document: "34.567.890/0001-22",
      category: "Laticinios",
      paymentTerms: "15 dias",
      status: "active",
    },
    {
      id: "sup-embalagens",
      name: "Embalagens Premium",
      document: "45.678.901/0001-33",
      category: "Embalagens",
      paymentTerms: "30 dias",
      status: "active",
    },
  ],
  customers: [
    {
      id: "cus-maria",
      name: "Maria Silva",
      phone: "(11) 98123-4567",
      averageTicket: 48.2,
      totalSpent: 1240,
      lastPurchaseAt: today,
    },
    {
      id: "cus-joao",
      name: "Joao Pereira",
      phone: "(11) 97456-1122",
      averageTicket: 32.5,
      totalSpent: 980,
      lastPurchaseAt: today,
    },
    {
      id: "cus-ana",
      name: "Ana Lima",
      phone: "(11) 99012-8877",
      averageTicket: 65,
      totalSpent: 2890,
      lastPurchaseAt: today,
    },
  ],
  employees: [
    {
      id: "emp-renata",
      name: "Renata Alves",
      role: "Gerente",
      hiredAt: "2024-03-10",
      status: "active",
    },
    {
      id: "emp-bruno",
      name: "Bruno Castro",
      role: "Barista Chefe",
      hiredAt: "2024-06-22",
      status: "active",
    },
    {
      id: "emp-camila",
      name: "Camila Duarte",
      role: "Confeiteira",
      hiredAt: "2025-01-15",
      status: "active",
    },
    {
      id: "emp-diego",
      name: "Diego Lopes",
      role: "Atendente / Caixa",
      hiredAt: "2025-08-04",
      status: "active",
    },
    {
      id: "emp-elaine",
      name: "Elaine Souza",
      role: "Financeiro",
      hiredAt: "2024-11-02",
      status: "active",
    },
  ],
  orders: [],
  cashRegisters: [],
  financialRecords,
  purchases,
  auditLogs: [
    {
      id: "audit-seed-1",
      createdAt: `${today}T10:24:00.000Z`,
      userId: "usr-cashier",
      action: "Sistema iniciado",
      details: "Seeds realistas carregados para testes internos.",
    },
  ],
};
